// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/home.proto

package shop_srv_home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HomeNavListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeNavListReq) Reset()         { *m = HomeNavListReq{} }
func (m *HomeNavListReq) String() string { return proto.CompactTextString(m) }
func (*HomeNavListReq) ProtoMessage()    {}
func (*HomeNavListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f70680a1e73242, []int{0}
}

func (m *HomeNavListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeNavListReq.Unmarshal(m, b)
}
func (m *HomeNavListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeNavListReq.Marshal(b, m, deterministic)
}
func (m *HomeNavListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeNavListReq.Merge(m, src)
}
func (m *HomeNavListReq) XXX_Size() int {
	return xxx_messageInfo_HomeNavListReq.Size(m)
}
func (m *HomeNavListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeNavListReq.DiscardUnknown(m)
}

var xxx_messageInfo_HomeNavListReq proto.InternalMessageInfo

type HomeNav struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EnTitle              string   `protobuf:"bytes,3,opt,name=enTitle,proto3" json:"enTitle,omitempty"`
	ImgUrl               string   `protobuf:"bytes,4,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	Types                int32    `protobuf:"varint,5,opt,name=types,proto3" json:"types,omitempty"`
	ClassId              int32    `protobuf:"varint,6,opt,name=classId,proto3" json:"classId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeNav) Reset()         { *m = HomeNav{} }
func (m *HomeNav) String() string { return proto.CompactTextString(m) }
func (*HomeNav) ProtoMessage()    {}
func (*HomeNav) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f70680a1e73242, []int{1}
}

func (m *HomeNav) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeNav.Unmarshal(m, b)
}
func (m *HomeNav) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeNav.Marshal(b, m, deterministic)
}
func (m *HomeNav) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeNav.Merge(m, src)
}
func (m *HomeNav) XXX_Size() int {
	return xxx_messageInfo_HomeNav.Size(m)
}
func (m *HomeNav) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeNav.DiscardUnknown(m)
}

var xxx_messageInfo_HomeNav proto.InternalMessageInfo

func (m *HomeNav) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HomeNav) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HomeNav) GetEnTitle() string {
	if m != nil {
		return m.EnTitle
	}
	return ""
}

func (m *HomeNav) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *HomeNav) GetTypes() int32 {
	if m != nil {
		return m.Types
	}
	return 0
}

func (m *HomeNav) GetClassId() int32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

type HomeNavListResp struct {
	HomeNavLists         []*HomeNav `protobuf:"bytes,1,rep,name=homeNavLists,proto3" json:"homeNavLists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HomeNavListResp) Reset()         { *m = HomeNavListResp{} }
func (m *HomeNavListResp) String() string { return proto.CompactTextString(m) }
func (*HomeNavListResp) ProtoMessage()    {}
func (*HomeNavListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f70680a1e73242, []int{2}
}

func (m *HomeNavListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeNavListResp.Unmarshal(m, b)
}
func (m *HomeNavListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeNavListResp.Marshal(b, m, deterministic)
}
func (m *HomeNavListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeNavListResp.Merge(m, src)
}
func (m *HomeNavListResp) XXX_Size() int {
	return xxx_messageInfo_HomeNavListResp.Size(m)
}
func (m *HomeNavListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeNavListResp.DiscardUnknown(m)
}

var xxx_messageInfo_HomeNavListResp proto.InternalMessageInfo

func (m *HomeNavListResp) GetHomeNavLists() []*HomeNav {
	if m != nil {
		return m.HomeNavLists
	}
	return nil
}

type HomeContentListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeContentListReq) Reset()         { *m = HomeContentListReq{} }
func (m *HomeContentListReq) String() string { return proto.CompactTextString(m) }
func (*HomeContentListReq) ProtoMessage()    {}
func (*HomeContentListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f70680a1e73242, []int{3}
}

func (m *HomeContentListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeContentListReq.Unmarshal(m, b)
}
func (m *HomeContentListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeContentListReq.Marshal(b, m, deterministic)
}
func (m *HomeContentListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeContentListReq.Merge(m, src)
}
func (m *HomeContentListReq) XXX_Size() int {
	return xxx_messageInfo_HomeContentListReq.Size(m)
}
func (m *HomeContentListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeContentListReq.DiscardUnknown(m)
}

var xxx_messageInfo_HomeContentListReq proto.InternalMessageInfo

type HomeContentListResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeContentListResp) Reset()         { *m = HomeContentListResp{} }
func (m *HomeContentListResp) String() string { return proto.CompactTextString(m) }
func (*HomeContentListResp) ProtoMessage()    {}
func (*HomeContentListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f70680a1e73242, []int{4}
}

func (m *HomeContentListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeContentListResp.Unmarshal(m, b)
}
func (m *HomeContentListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeContentListResp.Marshal(b, m, deterministic)
}
func (m *HomeContentListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeContentListResp.Merge(m, src)
}
func (m *HomeContentListResp) XXX_Size() int {
	return xxx_messageInfo_HomeContentListResp.Size(m)
}
func (m *HomeContentListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeContentListResp.DiscardUnknown(m)
}

var xxx_messageInfo_HomeContentListResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HomeNavListReq)(nil), "shop.srv.home.HomeNavListReq")
	proto.RegisterType((*HomeNav)(nil), "shop.srv.home.HomeNav")
	proto.RegisterType((*HomeNavListResp)(nil), "shop.srv.home.HomeNavListResp")
	proto.RegisterType((*HomeContentListReq)(nil), "shop.srv.home.HomeContentListReq")
	proto.RegisterType((*HomeContentListResp)(nil), "shop.srv.home.HomeContentListResp")
}

func init() { proto.RegisterFile("proto/home.proto", fileDescriptor_e4f70680a1e73242) }

var fileDescriptor_e4f70680a1e73242 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0x6b, 0x3b, 0x7c, 0x9d, 0x73, 0xc4, 0x39, 0xc2, 0x40, 0xa9, 0x39, 0xf5, 0x54,
	0x61, 0xde, 0xbc, 0x0a, 0xa2, 0xa0, 0x3b, 0x54, 0xc5, 0xf3, 0x5c, 0x83, 0x0d, 0xb4, 0x4d, 0xec,
	0x0b, 0x05, 0x3f, 0x86, 0x5f, 0xc6, 0xcf, 0x27, 0xc9, 0x5a, 0xa4, 0x38, 0xf4, 0x96, 0xff, 0xef,
	0xff, 0xde, 0x3f, 0xef, 0x25, 0x30, 0xd5, 0x8d, 0x32, 0xea, 0xa2, 0x50, 0x95, 0x48, 0xdd, 0x91,
	0x1e, 0x62, 0xa1, 0x74, 0x8a, 0x4d, 0x9b, 0x5a, 0xc8, 0xa7, 0x30, 0xb9, 0x55, 0x95, 0x58, 0xad,
	0xdb, 0x7b, 0x89, 0x26, 0x13, 0xef, 0xfc, 0x93, 0xc0, 0xa8, 0x43, 0x74, 0x02, 0x9e, 0xcc, 0x19,
	0x89, 0x49, 0xe2, 0x67, 0x9e, 0xcc, 0xe9, 0x0c, 0x02, 0x23, 0x4d, 0x29, 0x98, 0x17, 0x93, 0xe4,
	0x20, 0xdb, 0x0a, 0xca, 0x60, 0x24, 0xea, 0x27, 0xc7, 0x7d, 0xc7, 0x7b, 0x49, 0xe7, 0x10, 0xca,
	0xea, 0xed, 0xb9, 0x29, 0xd9, 0xbe, 0x33, 0x3a, 0xe5, 0x72, 0x3e, 0xb4, 0x40, 0x16, 0xc4, 0x24,
	0x09, 0xb2, 0xad, 0xb0, 0x39, 0x9b, 0x72, 0x8d, 0x78, 0x97, 0xb3, 0xd0, 0xf1, 0x5e, 0xf2, 0x07,
	0x38, 0x1a, 0x4c, 0x89, 0x9a, 0x5e, 0xc1, 0xb8, 0xf8, 0x41, 0xc8, 0x48, 0xec, 0x27, 0xd1, 0x72,
	0x9e, 0x0e, 0xd6, 0x4b, 0xbb, 0xae, 0x6c, 0x50, 0xcb, 0x67, 0x40, 0xad, 0x71, 0xad, 0x6a, 0x23,
	0x6a, 0xd3, 0x2f, 0x7e, 0x02, 0xc7, 0xbf, 0x28, 0xea, 0xe5, 0x17, 0x81, 0xc8, 0xf2, 0x47, 0xd1,
	0xb4, 0x72, 0x23, 0xe8, 0x0a, 0xa2, 0x1b, 0x59, 0xe7, 0xfd, 0x13, 0x9d, 0xee, 0xbe, 0xb1, 0x0b,
	0x5d, 0x9c, 0xfd, 0x65, 0xa3, 0xe6, 0x7b, 0xf4, 0x05, 0xc6, 0x7d, 0x9e, 0xa5, 0xf4, 0x7c, 0x47,
	0xc7, 0x70, 0xd2, 0x05, 0xff, 0xaf, 0xc4, 0x06, 0xbf, 0x86, 0xee, 0xc3, 0x2f, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x4f, 0x70, 0x14, 0x91, 0x04, 0x02, 0x00, 0x00,
}
