// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quote.proto

package fotune_srv_quote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

// Any from public import google/protobuf/any.proto
type Any = any.Any

type GetTicksSymbolReq struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicksSymbolReq) Reset()         { *m = GetTicksSymbolReq{} }
func (m *GetTicksSymbolReq) String() string { return proto.CompactTextString(m) }
func (*GetTicksSymbolReq) ProtoMessage()    {}
func (*GetTicksSymbolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12e4b46109c2c385, []int{0}
}

func (m *GetTicksSymbolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicksSymbolReq.Unmarshal(m, b)
}
func (m *GetTicksSymbolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicksSymbolReq.Marshal(b, m, deterministic)
}
func (m *GetTicksSymbolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicksSymbolReq.Merge(m, src)
}
func (m *GetTicksSymbolReq) XXX_Size() int {
	return xxx_messageInfo_GetTicksSymbolReq.Size(m)
}
func (m *GetTicksSymbolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicksSymbolReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicksSymbolReq proto.InternalMessageInfo

func (m *GetTicksSymbolReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetTicksSymbolReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type GetTicksReq struct {
	All                  bool     `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicksReq) Reset()         { *m = GetTicksReq{} }
func (m *GetTicksReq) String() string { return proto.CompactTextString(m) }
func (*GetTicksReq) ProtoMessage()    {}
func (*GetTicksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12e4b46109c2c385, []int{1}
}

func (m *GetTicksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicksReq.Unmarshal(m, b)
}
func (m *GetTicksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicksReq.Marshal(b, m, deterministic)
}
func (m *GetTicksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicksReq.Merge(m, src)
}
func (m *GetTicksReq) XXX_Size() int {
	return xxx_messageInfo_GetTicksReq.Size(m)
}
func (m *GetTicksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicksReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicksReq proto.InternalMessageInfo

func (m *GetTicksReq) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *GetTicksReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type TickResp struct {
	Ticks                []byte   `protobuf:"bytes,1,opt,name=ticks,proto3" json:"ticks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickResp) Reset()         { *m = TickResp{} }
func (m *TickResp) String() string { return proto.CompactTextString(m) }
func (*TickResp) ProtoMessage()    {}
func (*TickResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12e4b46109c2c385, []int{2}
}

func (m *TickResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickResp.Unmarshal(m, b)
}
func (m *TickResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickResp.Marshal(b, m, deterministic)
}
func (m *TickResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickResp.Merge(m, src)
}
func (m *TickResp) XXX_Size() int {
	return xxx_messageInfo_TickResp.Size(m)
}
func (m *TickResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TickResp.DiscardUnknown(m)
}

var xxx_messageInfo_TickResp proto.InternalMessageInfo

func (m *TickResp) GetTicks() []byte {
	if m != nil {
		return m.Ticks
	}
	return nil
}

type RateUsdRmb struct {
	InstrumentID         string   `protobuf:"bytes,1,opt,name=InstrumentID,proto3" json:"InstrumentID,omitempty"`
	Rate                 string   `protobuf:"bytes,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateUsdRmb) Reset()         { *m = RateUsdRmb{} }
func (m *RateUsdRmb) String() string { return proto.CompactTextString(m) }
func (*RateUsdRmb) ProtoMessage()    {}
func (*RateUsdRmb) Descriptor() ([]byte, []int) {
	return fileDescriptor_12e4b46109c2c385, []int{3}
}

func (m *RateUsdRmb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateUsdRmb.Unmarshal(m, b)
}
func (m *RateUsdRmb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateUsdRmb.Marshal(b, m, deterministic)
}
func (m *RateUsdRmb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateUsdRmb.Merge(m, src)
}
func (m *RateUsdRmb) XXX_Size() int {
	return xxx_messageInfo_RateUsdRmb.Size(m)
}
func (m *RateUsdRmb) XXX_DiscardUnknown() {
	xxx_messageInfo_RateUsdRmb.DiscardUnknown(m)
}

var xxx_messageInfo_RateUsdRmb proto.InternalMessageInfo

func (m *RateUsdRmb) GetInstrumentID() string {
	if m != nil {
		return m.InstrumentID
	}
	return ""
}

func (m *RateUsdRmb) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *RateUsdRmb) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTicksSymbolReq)(nil), "GetTicksSymbolReq")
	proto.RegisterType((*GetTicksReq)(nil), "GetTicksReq")
	proto.RegisterType((*TickResp)(nil), "TickResp")
	proto.RegisterType((*RateUsdRmb)(nil), "RateUsdRmb")
}

func init() { proto.RegisterFile("quote.proto", fileDescriptor_12e4b46109c2c385) }

var fileDescriptor_12e4b46109c2c385 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x29, 0xbc, 0xc7, 0x83, 0xa1, 0xc9, 0x7b, 0x6f, 0x42, 0x08, 0x56, 0x13, 0x49, 0x4f,
	0x9e, 0x16, 0xd4, 0x23, 0xf1, 0x62, 0x24, 0x84, 0x93, 0x58, 0x30, 0x26, 0x5e, 0x48, 0x8b, 0x03,
	0x34, 0xd0, 0x1f, 0xb4, 0x53, 0x02, 0xff, 0xae, 0x7f, 0x89, 0xe9, 0x76, 0x2b, 0x82, 0x86, 0xdb,
	0x7e, 0x77, 0xe6, 0x33, 0x3b, 0xf3, 0xdd, 0x81, 0xda, 0x3a, 0x09, 0x98, 0x44, 0x18, 0x05, 0x1c,
	0x18, 0xe7, 0xf3, 0x20, 0x98, 0xaf, 0xa8, 0x2d, 0x95, 0x93, 0xcc, 0xda, 0xe4, 0x85, 0xbc, 0x53,
	0xc1, 0xcb, 0xe3, 0x20, 0xbb, 0x1e, 0xc5, 0x6c, 0x7b, 0xa1, 0x4a, 0x38, 0x3b, 0x4e, 0xb0, 0x7d,
	0xc5, 0x9a, 0x7d, 0xf8, 0xdf, 0x27, 0x1e, 0xbb, 0xd3, 0x65, 0x3c, 0xda, 0x79, 0x4e, 0xb0, 0xb2,
	0x68, 0x8d, 0x0d, 0x28, 0xc7, 0x52, 0x34, 0xb5, 0x96, 0x76, 0x55, 0xb5, 0x94, 0x42, 0x03, 0x2a,
	0xb4, 0x9d, 0x2e, 0x6c, 0x7f, 0x4e, 0xcd, 0xa2, 0x8c, 0x7c, 0x6a, 0xb3, 0x0b, 0xb5, 0xbc, 0x50,
	0x5a, 0xe2, 0x1f, 0x94, 0xec, 0x55, 0xc6, 0x57, 0xac, 0xf4, 0x78, 0x12, 0x6e, 0x41, 0x25, 0x25,
	0x2d, 0x8a, 0x43, 0xac, 0xc3, 0x6f, 0x4e, 0xab, 0x48, 0x56, 0xb7, 0x32, 0x61, 0x3a, 0x00, 0x96,
	0xcd, 0xf4, 0x1c, 0xbf, 0x59, 0x9e, 0x83, 0x26, 0xe8, 0x03, 0x3f, 0xe6, 0x28, 0xf1, 0xc8, 0xe7,
	0xc1, 0x83, 0x6a, 0xf3, 0xe0, 0x0e, 0x11, 0x7e, 0xa5, 0x84, 0x7a, 0x4b, 0x9e, 0xf1, 0x02, 0xaa,
	0xe3, 0xdc, 0x9b, 0x66, 0x49, 0x06, 0xf6, 0x17, 0x37, 0xef, 0x1a, 0xe8, 0x4f, 0xa9, 0xe9, 0x23,
	0x8a, 0x36, 0xee, 0x94, 0xf0, 0x1a, 0xea, 0xf9, 0x4c, 0x2f, 0x2e, 0x2f, 0x7a, 0xaa, 0x5d, 0xd4,
	0xc5, 0x97, 0x51, 0x8d, 0xaa, 0xc8, 0x7b, 0x37, 0x0b, 0x78, 0x07, 0xc6, 0x4f, 0x48, 0xe6, 0x2d,
	0xa2, 0xf8, 0x66, 0xf6, 0x21, 0x2e, 0xe0, 0xef, 0x88, 0x23, 0xb2, 0xbd, 0xc7, 0x25, 0x6d, 0x65,
	0xe2, 0x89, 0xc7, 0x3a, 0x1a, 0x76, 0xe0, 0x4f, 0x9f, 0x58, 0xce, 0xd6, 0x10, 0xd9, 0x2f, 0x8b,
	0xfc, 0x97, 0x45, 0x2f, 0xdd, 0x11, 0xa3, 0x26, 0xf6, 0xc6, 0x99, 0x85, 0xfb, 0xfa, 0x2b, 0x8a,
	0xee, 0x2c, 0xe0, 0xc4, 0xa7, 0x49, 0x1c, 0x6d, 0x26, 0x72, 0xcb, 0x86, 0xda, 0xb0, 0xe8, 0x94,
	0x25, 0x78, 0xfb, 0x11, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xf4, 0x6a, 0x4d, 0x79, 0x02, 0x00, 0x00,
}
