// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exorder.proto

package fotune_srv_exchange

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type StrategyProfitCompensateReq struct {
	StrategyId           string   `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyProfitCompensateReq) Reset()         { *m = StrategyProfitCompensateReq{} }
func (m *StrategyProfitCompensateReq) String() string { return proto.CompactTextString(m) }
func (*StrategyProfitCompensateReq) ProtoMessage()    {}
func (*StrategyProfitCompensateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{0}
}

func (m *StrategyProfitCompensateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyProfitCompensateReq.Unmarshal(m, b)
}
func (m *StrategyProfitCompensateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyProfitCompensateReq.Marshal(b, m, deterministic)
}
func (m *StrategyProfitCompensateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyProfitCompensateReq.Merge(m, src)
}
func (m *StrategyProfitCompensateReq) XXX_Size() int {
	return xxx_messageInfo_StrategyProfitCompensateReq.Size(m)
}
func (m *StrategyProfitCompensateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyProfitCompensateReq.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyProfitCompensateReq proto.InternalMessageInfo

func (m *StrategyProfitCompensateReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *StrategyProfitCompensateReq) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type SymbolWithRate struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	RateYear             string   `protobuf:"bytes,2,opt,name=rateYear,proto3" json:"rateYear,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymbolWithRate) Reset()         { *m = SymbolWithRate{} }
func (m *SymbolWithRate) String() string { return proto.CompactTextString(m) }
func (*SymbolWithRate) ProtoMessage()    {}
func (*SymbolWithRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{1}
}

func (m *SymbolWithRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymbolWithRate.Unmarshal(m, b)
}
func (m *SymbolWithRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymbolWithRate.Marshal(b, m, deterministic)
}
func (m *SymbolWithRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymbolWithRate.Merge(m, src)
}
func (m *SymbolWithRate) XXX_Size() int {
	return xxx_messageInfo_SymbolWithRate.Size(m)
}
func (m *SymbolWithRate) XXX_DiscardUnknown() {
	xxx_messageInfo_SymbolWithRate.DiscardUnknown(m)
}

var xxx_messageInfo_SymbolWithRate proto.InternalMessageInfo

func (m *SymbolWithRate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SymbolWithRate) GetRateYear() string {
	if m != nil {
		return m.RateYear
	}
	return ""
}

func (m *SymbolWithRate) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type SymbolRankWithRateYearResp struct {
	Data                 []*SymbolWithRate `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SymbolRankWithRateYearResp) Reset()         { *m = SymbolRankWithRateYearResp{} }
func (m *SymbolRankWithRateYearResp) String() string { return proto.CompactTextString(m) }
func (*SymbolRankWithRateYearResp) ProtoMessage()    {}
func (*SymbolRankWithRateYearResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{2}
}

func (m *SymbolRankWithRateYearResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymbolRankWithRateYearResp.Unmarshal(m, b)
}
func (m *SymbolRankWithRateYearResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymbolRankWithRateYearResp.Marshal(b, m, deterministic)
}
func (m *SymbolRankWithRateYearResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymbolRankWithRateYearResp.Merge(m, src)
}
func (m *SymbolRankWithRateYearResp) XXX_Size() int {
	return xxx_messageInfo_SymbolRankWithRateYearResp.Size(m)
}
func (m *SymbolRankWithRateYearResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SymbolRankWithRateYearResp.DiscardUnknown(m)
}

var xxx_messageInfo_SymbolRankWithRateYearResp proto.InternalMessageInfo

func (m *SymbolRankWithRateYearResp) GetData() []*SymbolWithRate {
	if m != nil {
		return m.Data
	}
	return nil
}

type AssertsResp struct {
	Asserts              string   `protobuf:"bytes,1,opt,name=asserts,proto3" json:"asserts,omitempty"`
	Profit               string   `protobuf:"bytes,2,opt,name=profit,proto3" json:"profit,omitempty"`
	ProfitPercent        string   `protobuf:"bytes,3,opt,name=profitPercent,proto3" json:"profitPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssertsResp) Reset()         { *m = AssertsResp{} }
func (m *AssertsResp) String() string { return proto.CompactTextString(m) }
func (*AssertsResp) ProtoMessage()    {}
func (*AssertsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{3}
}

func (m *AssertsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssertsResp.Unmarshal(m, b)
}
func (m *AssertsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssertsResp.Marshal(b, m, deterministic)
}
func (m *AssertsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssertsResp.Merge(m, src)
}
func (m *AssertsResp) XXX_Size() int {
	return xxx_messageInfo_AssertsResp.Size(m)
}
func (m *AssertsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AssertsResp.DiscardUnknown(m)
}

var xxx_messageInfo_AssertsResp proto.InternalMessageInfo

func (m *AssertsResp) GetAsserts() string {
	if m != nil {
		return m.Asserts
	}
	return ""
}

func (m *AssertsResp) GetProfit() string {
	if m != nil {
		return m.Profit
	}
	return ""
}

func (m *AssertsResp) GetProfitPercent() string {
	if m != nil {
		return m.ProfitPercent
	}
	return ""
}

type TradeSymbolReq struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Coin                 string   `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeSymbolReq) Reset()         { *m = TradeSymbolReq{} }
func (m *TradeSymbolReq) String() string { return proto.CompactTextString(m) }
func (*TradeSymbolReq) ProtoMessage()    {}
func (*TradeSymbolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{4}
}

func (m *TradeSymbolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSymbolReq.Unmarshal(m, b)
}
func (m *TradeSymbolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSymbolReq.Marshal(b, m, deterministic)
}
func (m *TradeSymbolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSymbolReq.Merge(m, src)
}
func (m *TradeSymbolReq) XXX_Size() int {
	return xxx_messageInfo_TradeSymbolReq.Size(m)
}
func (m *TradeSymbolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSymbolReq.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSymbolReq proto.InternalMessageInfo

func (m *TradeSymbolReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *TradeSymbolReq) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

type Symbol struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Unit                 string   `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Change               string   `protobuf:"bytes,6,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{5}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Symbol) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Symbol) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Symbol) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Symbol) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Symbol) GetChange() string {
	if m != nil {
		return m.Change
	}
	return ""
}

type GetSymbolsResp struct {
	Symbols              []*Symbol `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSymbolsResp) Reset()         { *m = GetSymbolsResp{} }
func (m *GetSymbolsResp) String() string { return proto.CompactTextString(m) }
func (*GetSymbolsResp) ProtoMessage()    {}
func (*GetSymbolsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{6}
}

func (m *GetSymbolsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolsResp.Unmarshal(m, b)
}
func (m *GetSymbolsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolsResp.Marshal(b, m, deterministic)
}
func (m *GetSymbolsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolsResp.Merge(m, src)
}
func (m *GetSymbolsResp) XXX_Size() int {
	return xxx_messageInfo_GetSymbolsResp.Size(m)
}
func (m *GetSymbolsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolsResp proto.InternalMessageInfo

func (m *GetSymbolsResp) GetSymbols() []*Symbol {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type ExChangeList struct {
	Exchanges            []byte   `protobuf:"bytes,1,opt,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExChangeList) Reset()         { *m = ExChangeList{} }
func (m *ExChangeList) String() string { return proto.CompactTextString(m) }
func (*ExChangeList) ProtoMessage()    {}
func (*ExChangeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{7}
}

func (m *ExChangeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExChangeList.Unmarshal(m, b)
}
func (m *ExChangeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExChangeList.Marshal(b, m, deterministic)
}
func (m *ExChangeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExChangeList.Merge(m, src)
}
func (m *ExChangeList) XXX_Size() int {
	return xxx_messageInfo_ExChangeList.Size(m)
}
func (m *ExChangeList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExChangeList.DiscardUnknown(m)
}

var xxx_messageInfo_ExChangeList proto.InternalMessageInfo

func (m *ExChangeList) GetExchanges() []byte {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type UserApiReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiID                int64    `protobuf:"varint,2,opt,name=ApiID,proto3" json:"ApiID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserApiReq) Reset()         { *m = UserApiReq{} }
func (m *UserApiReq) String() string { return proto.CompactTextString(m) }
func (*UserApiReq) ProtoMessage()    {}
func (*UserApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{8}
}

func (m *UserApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserApiReq.Unmarshal(m, b)
}
func (m *UserApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserApiReq.Marshal(b, m, deterministic)
}
func (m *UserApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserApiReq.Merge(m, src)
}
func (m *UserApiReq) XXX_Size() int {
	return xxx_messageInfo_UserApiReq.Size(m)
}
func (m *UserApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserApiReq proto.InternalMessageInfo

func (m *UserApiReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserApiReq) GetApiID() int64 {
	if m != nil {
		return m.ApiID
	}
	return 0
}

type UserApiKeyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey               string   `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserApiKeyReq) Reset()         { *m = UserApiKeyReq{} }
func (m *UserApiKeyReq) String() string { return proto.CompactTextString(m) }
func (*UserApiKeyReq) ProtoMessage()    {}
func (*UserApiKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{9}
}

func (m *UserApiKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserApiKeyReq.Unmarshal(m, b)
}
func (m *UserApiKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserApiKeyReq.Marshal(b, m, deterministic)
}
func (m *UserApiKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserApiKeyReq.Merge(m, src)
}
func (m *UserApiKeyReq) XXX_Size() int {
	return xxx_messageInfo_UserApiKeyReq.Size(m)
}
func (m *UserApiKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserApiKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserApiKeyReq proto.InternalMessageInfo

func (m *UserApiKeyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserApiKeyReq) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type ExchangeApi struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ExchangeID           int64    `protobuf:"varint,2,opt,name=ExchangeID,proto3" json:"ExchangeID,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Passphrase           string   `protobuf:"bytes,5,opt,name=Passphrase,proto3" json:"Passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeApi) Reset()         { *m = ExchangeApi{} }
func (m *ExchangeApi) String() string { return proto.CompactTextString(m) }
func (*ExchangeApi) ProtoMessage()    {}
func (*ExchangeApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{10}
}

func (m *ExchangeApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeApi.Unmarshal(m, b)
}
func (m *ExchangeApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeApi.Marshal(b, m, deterministic)
}
func (m *ExchangeApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeApi.Merge(m, src)
}
func (m *ExchangeApi) XXX_Size() int {
	return xxx_messageInfo_ExchangeApi.Size(m)
}
func (m *ExchangeApi) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeApi.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeApi proto.InternalMessageInfo

func (m *ExchangeApi) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ExchangeApi) GetExchangeID() int64 {
	if m != nil {
		return m.ExchangeID
	}
	return 0
}

func (m *ExchangeApi) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ExchangeApi) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ExchangeApi) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type ExchangeApiResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	ExchangeName         string   `protobuf:"bytes,3,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	ApiKey               string   `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Passphrase           string   `protobuf:"bytes,6,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeApiResp) Reset()         { *m = ExchangeApiResp{} }
func (m *ExchangeApiResp) String() string { return proto.CompactTextString(m) }
func (*ExchangeApiResp) ProtoMessage()    {}
func (*ExchangeApiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{11}
}

func (m *ExchangeApiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeApiResp.Unmarshal(m, b)
}
func (m *ExchangeApiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeApiResp.Marshal(b, m, deterministic)
}
func (m *ExchangeApiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeApiResp.Merge(m, src)
}
func (m *ExchangeApiResp) XXX_Size() int {
	return xxx_messageInfo_ExchangeApiResp.Size(m)
}
func (m *ExchangeApiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeApiResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeApiResp proto.InternalMessageInfo

func (m *ExchangeApiResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ExchangeApiResp) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeApiResp) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *ExchangeApiResp) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ExchangeApiResp) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ExchangeApiResp) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UpdateExchangeApiReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ExchangeID           int64    `protobuf:"varint,2,opt,name=ExchangeID,proto3" json:"ExchangeID,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Passphrase           string   `protobuf:"bytes,5,opt,name=Passphrase,proto3" json:"Passphrase,omitempty"`
	ApiID                int64    `protobuf:"varint,6,opt,name=ApiID,proto3" json:"ApiID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateExchangeApiReq) Reset()         { *m = UpdateExchangeApiReq{} }
func (m *UpdateExchangeApiReq) String() string { return proto.CompactTextString(m) }
func (*UpdateExchangeApiReq) ProtoMessage()    {}
func (*UpdateExchangeApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{12}
}

func (m *UpdateExchangeApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateExchangeApiReq.Unmarshal(m, b)
}
func (m *UpdateExchangeApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateExchangeApiReq.Marshal(b, m, deterministic)
}
func (m *UpdateExchangeApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateExchangeApiReq.Merge(m, src)
}
func (m *UpdateExchangeApiReq) XXX_Size() int {
	return xxx_messageInfo_UpdateExchangeApiReq.Size(m)
}
func (m *UpdateExchangeApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateExchangeApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateExchangeApiReq proto.InternalMessageInfo

func (m *UpdateExchangeApiReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateExchangeApiReq) GetExchangeID() int64 {
	if m != nil {
		return m.ExchangeID
	}
	return 0
}

func (m *UpdateExchangeApiReq) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *UpdateExchangeApiReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *UpdateExchangeApiReq) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *UpdateExchangeApiReq) GetApiID() int64 {
	if m != nil {
		return m.ApiID
	}
	return 0
}

type GetExApiReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExApiReq) Reset()         { *m = GetExApiReq{} }
func (m *GetExApiReq) String() string { return proto.CompactTextString(m) }
func (*GetExApiReq) ProtoMessage()    {}
func (*GetExApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{13}
}

func (m *GetExApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExApiReq.Unmarshal(m, b)
}
func (m *GetExApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExApiReq.Marshal(b, m, deterministic)
}
func (m *GetExApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExApiReq.Merge(m, src)
}
func (m *GetExApiReq) XXX_Size() int {
	return xxx_messageInfo_GetExApiReq.Size(m)
}
func (m *GetExApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExApiReq proto.InternalMessageInfo

func (m *GetExApiReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ExApiResp struct {
	ExApiList            []byte   `protobuf:"bytes,1,opt,name=ExApiList,proto3" json:"ExApiList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExApiResp) Reset()         { *m = ExApiResp{} }
func (m *ExApiResp) String() string { return proto.CompactTextString(m) }
func (*ExApiResp) ProtoMessage()    {}
func (*ExApiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{14}
}

func (m *ExApiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExApiResp.Unmarshal(m, b)
}
func (m *ExApiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExApiResp.Marshal(b, m, deterministic)
}
func (m *ExApiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExApiResp.Merge(m, src)
}
func (m *ExApiResp) XXX_Size() int {
	return xxx_messageInfo_ExApiResp.Size(m)
}
func (m *ExApiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExApiResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExApiResp proto.InternalMessageInfo

func (m *ExApiResp) GetExApiList() []byte {
	if m != nil {
		return m.ExApiList
	}
	return nil
}

type GetTradeListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTradeListReq) Reset()         { *m = GetTradeListReq{} }
func (m *GetTradeListReq) String() string { return proto.CompactTextString(m) }
func (*GetTradeListReq) ProtoMessage()    {}
func (*GetTradeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{15}
}

func (m *GetTradeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradeListReq.Unmarshal(m, b)
}
func (m *GetTradeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradeListReq.Marshal(b, m, deterministic)
}
func (m *GetTradeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradeListReq.Merge(m, src)
}
func (m *GetTradeListReq) XXX_Size() int {
	return xxx_messageInfo_GetTradeListReq.Size(m)
}
func (m *GetTradeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradeListReq proto.InternalMessageInfo

func (m *GetTradeListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetTradeListReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *GetTradeListReq) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetTradeListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type TradeListResp struct {
	TradeList            []byte   `protobuf:"bytes,1,opt,name=TradeList,proto3" json:"TradeList,omitempty"`
	TradeCount           int32    `protobuf:"varint,2,opt,name=tradeCount,proto3" json:"tradeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeListResp) Reset()         { *m = TradeListResp{} }
func (m *TradeListResp) String() string { return proto.CompactTextString(m) }
func (*TradeListResp) ProtoMessage()    {}
func (*TradeListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{16}
}

func (m *TradeListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeListResp.Unmarshal(m, b)
}
func (m *TradeListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeListResp.Marshal(b, m, deterministic)
}
func (m *TradeListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeListResp.Merge(m, src)
}
func (m *TradeListResp) XXX_Size() int {
	return xxx_messageInfo_TradeListResp.Size(m)
}
func (m *TradeListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeListResp.DiscardUnknown(m)
}

var xxx_messageInfo_TradeListResp proto.InternalMessageInfo

func (m *TradeListResp) GetTradeList() []byte {
	if m != nil {
		return m.TradeList
	}
	return nil
}

func (m *TradeListResp) GetTradeCount() int32 {
	if m != nil {
		return m.TradeCount
	}
	return 0
}

type ProfitReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfitReq) Reset()         { *m = ProfitReq{} }
func (m *ProfitReq) String() string { return proto.CompactTextString(m) }
func (*ProfitReq) ProtoMessage()    {}
func (*ProfitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{17}
}

func (m *ProfitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitReq.Unmarshal(m, b)
}
func (m *ProfitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitReq.Marshal(b, m, deterministic)
}
func (m *ProfitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitReq.Merge(m, src)
}
func (m *ProfitReq) XXX_Size() int {
	return xxx_messageInfo_ProfitReq.Size(m)
}
func (m *ProfitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitReq proto.InternalMessageInfo

func (m *ProfitReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ProfitReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

type ProfitRealTimeResp struct {
	ProfitList           []byte   `protobuf:"bytes,1,opt,name=profitList,proto3" json:"profitList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfitRealTimeResp) Reset()         { *m = ProfitRealTimeResp{} }
func (m *ProfitRealTimeResp) String() string { return proto.CompactTextString(m) }
func (*ProfitRealTimeResp) ProtoMessage()    {}
func (*ProfitRealTimeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{18}
}

func (m *ProfitRealTimeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfitRealTimeResp.Unmarshal(m, b)
}
func (m *ProfitRealTimeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfitRealTimeResp.Marshal(b, m, deterministic)
}
func (m *ProfitRealTimeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfitRealTimeResp.Merge(m, src)
}
func (m *ProfitRealTimeResp) XXX_Size() int {
	return xxx_messageInfo_ProfitRealTimeResp.Size(m)
}
func (m *ProfitRealTimeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfitRealTimeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProfitRealTimeResp proto.InternalMessageInfo

func (m *ProfitRealTimeResp) GetProfitList() []byte {
	if m != nil {
		return m.ProfitList
	}
	return nil
}

type GetExchangePosReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExchangePosReq) Reset()         { *m = GetExchangePosReq{} }
func (m *GetExchangePosReq) String() string { return proto.CompactTextString(m) }
func (*GetExchangePosReq) ProtoMessage()    {}
func (*GetExchangePosReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{19}
}

func (m *GetExchangePosReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExchangePosReq.Unmarshal(m, b)
}
func (m *GetExchangePosReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExchangePosReq.Marshal(b, m, deterministic)
}
func (m *GetExchangePosReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExchangePosReq.Merge(m, src)
}
func (m *GetExchangePosReq) XXX_Size() int {
	return xxx_messageInfo_GetExchangePosReq.Size(m)
}
func (m *GetExchangePosReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExchangePosReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExchangePosReq proto.InternalMessageInfo

func (m *GetExchangePosReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetExchangePosReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type GetStrategyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStrategyReq) Reset()         { *m = GetStrategyReq{} }
func (m *GetStrategyReq) String() string { return proto.CompactTextString(m) }
func (*GetStrategyReq) ProtoMessage()    {}
func (*GetStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{20}
}

func (m *GetStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStrategyReq.Unmarshal(m, b)
}
func (m *GetStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStrategyReq.Marshal(b, m, deterministic)
}
func (m *GetStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStrategyReq.Merge(m, src)
}
func (m *GetStrategyReq) XXX_Size() int {
	return xxx_messageInfo_GetStrategyReq.Size(m)
}
func (m *GetStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStrategyReq proto.InternalMessageInfo

func (m *GetStrategyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserStrategyListResp struct {
	UserStrategyList     []*UserStrategyWithRate `protobuf:"bytes,1,rep,name=user_strategy_list,json=userStrategyList,proto3" json:"user_strategy_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UserStrategyListResp) Reset()         { *m = UserStrategyListResp{} }
func (m *UserStrategyListResp) String() string { return proto.CompactTextString(m) }
func (*UserStrategyListResp) ProtoMessage()    {}
func (*UserStrategyListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{21}
}

func (m *UserStrategyListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategyListResp.Unmarshal(m, b)
}
func (m *UserStrategyListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategyListResp.Marshal(b, m, deterministic)
}
func (m *UserStrategyListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategyListResp.Merge(m, src)
}
func (m *UserStrategyListResp) XXX_Size() int {
	return xxx_messageInfo_UserStrategyListResp.Size(m)
}
func (m *UserStrategyListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategyListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategyListResp proto.InternalMessageInfo

func (m *UserStrategyListResp) GetUserStrategyList() []*UserStrategyWithRate {
	if m != nil {
		return m.UserStrategyList
	}
	return nil
}

type SetUserStrategyApiReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserStrategyApiReq) Reset()         { *m = SetUserStrategyApiReq{} }
func (m *SetUserStrategyApiReq) String() string { return proto.CompactTextString(m) }
func (*SetUserStrategyApiReq) ProtoMessage()    {}
func (*SetUserStrategyApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{22}
}

func (m *SetUserStrategyApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStrategyApiReq.Unmarshal(m, b)
}
func (m *SetUserStrategyApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStrategyApiReq.Marshal(b, m, deterministic)
}
func (m *SetUserStrategyApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStrategyApiReq.Merge(m, src)
}
func (m *SetUserStrategyApiReq) XXX_Size() int {
	return xxx_messageInfo_SetUserStrategyApiReq.Size(m)
}
func (m *SetUserStrategyApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStrategyApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStrategyApiReq proto.InternalMessageInfo

func (m *SetUserStrategyApiReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetUserStrategyApiReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *SetUserStrategyApiReq) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type UserStrategyDetailReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStrategyDetailReq) Reset()         { *m = UserStrategyDetailReq{} }
func (m *UserStrategyDetailReq) String() string { return proto.CompactTextString(m) }
func (*UserStrategyDetailReq) ProtoMessage()    {}
func (*UserStrategyDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{23}
}

func (m *UserStrategyDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategyDetailReq.Unmarshal(m, b)
}
func (m *UserStrategyDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategyDetailReq.Marshal(b, m, deterministic)
}
func (m *UserStrategyDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategyDetailReq.Merge(m, src)
}
func (m *UserStrategyDetailReq) XXX_Size() int {
	return xxx_messageInfo_UserStrategyDetailReq.Size(m)
}
func (m *UserStrategyDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategyDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategyDetailReq proto.InternalMessageInfo

func (m *UserStrategyDetailReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStrategyDetailReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

type UserStrategy struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	ParentStrategyId     int64    `protobuf:"varint,4,opt,name=parent_strategy_id,json=parentStrategyId,proto3" json:"parent_strategy_id,omitempty"`
	Platform             string   `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	ApiKey               string   `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Balance              string   `protobuf:"bytes,7,opt,name=balance,proto3" json:"balance,omitempty"`
	State                int32    `protobuf:"varint,9,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStrategy) Reset()         { *m = UserStrategy{} }
func (m *UserStrategy) String() string { return proto.CompactTextString(m) }
func (*UserStrategy) ProtoMessage()    {}
func (*UserStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{24}
}

func (m *UserStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategy.Unmarshal(m, b)
}
func (m *UserStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategy.Marshal(b, m, deterministic)
}
func (m *UserStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategy.Merge(m, src)
}
func (m *UserStrategy) XXX_Size() int {
	return xxx_messageInfo_UserStrategy.Size(m)
}
func (m *UserStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategy proto.InternalMessageInfo

func (m *UserStrategy) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStrategy) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *UserStrategy) GetParentStrategyId() int64 {
	if m != nil {
		return m.ParentStrategyId
	}
	return 0
}

func (m *UserStrategy) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *UserStrategy) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *UserStrategy) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *UserStrategy) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type UserStrategyWithRate struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	ParentStrategyId     int64    `protobuf:"varint,3,opt,name=parent_strategy_id,json=parentStrategyId,proto3" json:"parent_strategy_id,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	ApiKey               string   `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Balance              string   `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	State                int32    `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	RunAt                string   `protobuf:"bytes,8,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	TotalProfit          string   `protobuf:"bytes,9,opt,name=total_profit,json=totalProfit,proto3" json:"total_profit,omitempty"`
	RealizeProfit        string   `protobuf:"bytes,10,opt,name=realize_profit,json=realizeProfit,proto3" json:"realize_profit,omitempty"`
	UnRealizeProfit      string   `protobuf:"bytes,11,opt,name=un_realize_profit,json=unRealizeProfit,proto3" json:"un_realize_profit,omitempty"`
	RateReturnYear       string   `protobuf:"bytes,12,opt,name=rate_return_year,json=rateReturnYear,proto3" json:"rate_return_year,omitempty"`
	Symbol               string   `protobuf:"bytes,13,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStrategyWithRate) Reset()         { *m = UserStrategyWithRate{} }
func (m *UserStrategyWithRate) String() string { return proto.CompactTextString(m) }
func (*UserStrategyWithRate) ProtoMessage()    {}
func (*UserStrategyWithRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{25}
}

func (m *UserStrategyWithRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategyWithRate.Unmarshal(m, b)
}
func (m *UserStrategyWithRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategyWithRate.Marshal(b, m, deterministic)
}
func (m *UserStrategyWithRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategyWithRate.Merge(m, src)
}
func (m *UserStrategyWithRate) XXX_Size() int {
	return xxx_messageInfo_UserStrategyWithRate.Size(m)
}
func (m *UserStrategyWithRate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategyWithRate.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategyWithRate proto.InternalMessageInfo

func (m *UserStrategyWithRate) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStrategyWithRate) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *UserStrategyWithRate) GetParentStrategyId() int64 {
	if m != nil {
		return m.ParentStrategyId
	}
	return 0
}

func (m *UserStrategyWithRate) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *UserStrategyWithRate) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *UserStrategyWithRate) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *UserStrategyWithRate) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UserStrategyWithRate) GetRunAt() string {
	if m != nil {
		return m.RunAt
	}
	return ""
}

func (m *UserStrategyWithRate) GetTotalProfit() string {
	if m != nil {
		return m.TotalProfit
	}
	return ""
}

func (m *UserStrategyWithRate) GetRealizeProfit() string {
	if m != nil {
		return m.RealizeProfit
	}
	return ""
}

func (m *UserStrategyWithRate) GetUnRealizeProfit() string {
	if m != nil {
		return m.UnRealizeProfit
	}
	return ""
}

func (m *UserStrategyWithRate) GetRateReturnYear() string {
	if m != nil {
		return m.RateReturnYear
	}
	return ""
}

func (m *UserStrategyWithRate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type StrategyList struct {
	StrategyList         []byte   `protobuf:"bytes,1,opt,name=strategyList,proto3" json:"strategyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyList) Reset()         { *m = StrategyList{} }
func (m *StrategyList) String() string { return proto.CompactTextString(m) }
func (*StrategyList) ProtoMessage()    {}
func (*StrategyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{26}
}

func (m *StrategyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyList.Unmarshal(m, b)
}
func (m *StrategyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyList.Marshal(b, m, deterministic)
}
func (m *StrategyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyList.Merge(m, src)
}
func (m *StrategyList) XXX_Size() int {
	return xxx_messageInfo_StrategyList.Size(m)
}
func (m *StrategyList) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyList.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyList proto.InternalMessageInfo

func (m *StrategyList) GetStrategyList() []byte {
	if m != nil {
		return m.StrategyList
	}
	return nil
}

type StrategyReq struct {
	PageNum              int32    `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyReq) Reset()         { *m = StrategyReq{} }
func (m *StrategyReq) String() string { return proto.CompactTextString(m) }
func (*StrategyReq) ProtoMessage()    {}
func (*StrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{27}
}

func (m *StrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyReq.Unmarshal(m, b)
}
func (m *StrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyReq.Marshal(b, m, deterministic)
}
func (m *StrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyReq.Merge(m, src)
}
func (m *StrategyReq) XXX_Size() int {
	return xxx_messageInfo_StrategyReq.Size(m)
}
func (m *StrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyReq proto.InternalMessageInfo

func (m *StrategyReq) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *StrategyReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SetUserStrategyBalanceReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Balance              float32  `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserStrategyBalanceReq) Reset()         { *m = SetUserStrategyBalanceReq{} }
func (m *SetUserStrategyBalanceReq) String() string { return proto.CompactTextString(m) }
func (*SetUserStrategyBalanceReq) ProtoMessage()    {}
func (*SetUserStrategyBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{28}
}

func (m *SetUserStrategyBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStrategyBalanceReq.Unmarshal(m, b)
}
func (m *SetUserStrategyBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStrategyBalanceReq.Marshal(b, m, deterministic)
}
func (m *SetUserStrategyBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStrategyBalanceReq.Merge(m, src)
}
func (m *SetUserStrategyBalanceReq) XXX_Size() int {
	return xxx_messageInfo_SetUserStrategyBalanceReq.Size(m)
}
func (m *SetUserStrategyBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStrategyBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStrategyBalanceReq proto.InternalMessageInfo

func (m *SetUserStrategyBalanceReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetUserStrategyBalanceReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *SetUserStrategyBalanceReq) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetStrategyDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStrategyDetail) Reset()         { *m = GetStrategyDetail{} }
func (m *GetStrategyDetail) String() string { return proto.CompactTextString(m) }
func (*GetStrategyDetail) ProtoMessage()    {}
func (*GetStrategyDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{29}
}

func (m *GetStrategyDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStrategyDetail.Unmarshal(m, b)
}
func (m *GetStrategyDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStrategyDetail.Marshal(b, m, deterministic)
}
func (m *GetStrategyDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStrategyDetail.Merge(m, src)
}
func (m *GetStrategyDetail) XXX_Size() int {
	return xxx_messageInfo_GetStrategyDetail.Size(m)
}
func (m *GetStrategyDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStrategyDetail.DiscardUnknown(m)
}

var xxx_messageInfo_GetStrategyDetail proto.InternalMessageInfo

func (m *GetStrategyDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Strategy struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	ExchangeName         string   `protobuf:"bytes,5,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	ExchangeId           int64    `protobuf:"varint,6,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Level                int32    `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	State                int32    `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strategy) Reset()         { *m = Strategy{} }
func (m *Strategy) String() string { return proto.CompactTextString(m) }
func (*Strategy) ProtoMessage()    {}
func (*Strategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{30}
}

func (m *Strategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strategy.Unmarshal(m, b)
}
func (m *Strategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strategy.Marshal(b, m, deterministic)
}
func (m *Strategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strategy.Merge(m, src)
}
func (m *Strategy) XXX_Size() int {
	return xxx_messageInfo_Strategy.Size(m)
}
func (m *Strategy) XXX_DiscardUnknown() {
	xxx_messageInfo_Strategy.DiscardUnknown(m)
}

var xxx_messageInfo_Strategy proto.InternalMessageInfo

func (m *Strategy) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Strategy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Strategy) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Strategy) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Strategy) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Strategy) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *Strategy) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Strategy) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type CreateStrategyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Balance              float32  `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStrategyReq) Reset()         { *m = CreateStrategyReq{} }
func (m *CreateStrategyReq) String() string { return proto.CompactTextString(m) }
func (*CreateStrategyReq) ProtoMessage()    {}
func (*CreateStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{31}
}

func (m *CreateStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStrategyReq.Unmarshal(m, b)
}
func (m *CreateStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStrategyReq.Marshal(b, m, deterministic)
}
func (m *CreateStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStrategyReq.Merge(m, src)
}
func (m *CreateStrategyReq) XXX_Size() int {
	return xxx_messageInfo_CreateStrategyReq.Size(m)
}
func (m *CreateStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStrategyReq proto.InternalMessageInfo

func (m *CreateStrategyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateStrategyReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateStrategyReq) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type TradeReq struct {
	TradeId              string               `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey               string               `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	OrderId              string               `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StrategyId           string               `protobuf:"bytes,5,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Direction            string               `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Volume               string               `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Commission           string               `protobuf:"bytes,8,opt,name=commission,proto3" json:"commission,omitempty"`
	Unit                 string               `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	Symbol               string               `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price                string               `protobuf:"bytes,11,opt,name=price,proto3" json:"price,omitempty"`
	TradeAt              *timestamp.Timestamp `protobuf:"bytes,12,opt,name=trade_at,json=tradeAt,proto3" json:"trade_at,omitempty"`
	Exchange             string               `protobuf:"bytes,13,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TradeReq) Reset()         { *m = TradeReq{} }
func (m *TradeReq) String() string { return proto.CompactTextString(m) }
func (*TradeReq) ProtoMessage()    {}
func (*TradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{32}
}

func (m *TradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeReq.Unmarshal(m, b)
}
func (m *TradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeReq.Marshal(b, m, deterministic)
}
func (m *TradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeReq.Merge(m, src)
}
func (m *TradeReq) XXX_Size() int {
	return xxx_messageInfo_TradeReq.Size(m)
}
func (m *TradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TradeReq proto.InternalMessageInfo

func (m *TradeReq) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *TradeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TradeReq) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *TradeReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *TradeReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *TradeReq) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *TradeReq) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *TradeReq) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *TradeReq) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *TradeReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TradeReq) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TradeReq) GetTradeAt() *timestamp.Timestamp {
	if m != nil {
		return m.TradeAt
	}
	return nil
}

func (m *TradeReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type OrderReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	StrategyId           string   `protobuf:"bytes,5,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Volume               string   `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Symbol               string   `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BuyPrice             string   `protobuf:"bytes,11,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice            string   `protobuf:"bytes,12,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	TradeAt              string   `protobuf:"bytes,13,opt,name=trade_at,json=tradeAt,proto3" json:"trade_at,omitempty"`
	Exchange             string   `protobuf:"bytes,14,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Unit                 string   `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderReq) Reset()         { *m = OrderReq{} }
func (m *OrderReq) String() string { return proto.CompactTextString(m) }
func (*OrderReq) ProtoMessage()    {}
func (*OrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{33}
}

func (m *OrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderReq.Unmarshal(m, b)
}
func (m *OrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderReq.Marshal(b, m, deterministic)
}
func (m *OrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderReq.Merge(m, src)
}
func (m *OrderReq) XXX_Size() int {
	return xxx_messageInfo_OrderReq.Size(m)
}
func (m *OrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderReq proto.InternalMessageInfo

func (m *OrderReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderReq) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *OrderReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *OrderReq) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *OrderReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderReq) GetBuyPrice() string {
	if m != nil {
		return m.BuyPrice
	}
	return ""
}

func (m *OrderReq) GetSellPrice() string {
	if m != nil {
		return m.SellPrice
	}
	return ""
}

func (m *OrderReq) GetTradeAt() string {
	if m != nil {
		return m.TradeAt
	}
	return ""
}

func (m *OrderReq) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderReq) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type ExchangePos struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Balance              string   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Available            string   `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	Frozen               string   `protobuf:"bytes,4,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	TotalUsdt            string   `protobuf:"bytes,7,opt,name=total_usdt,json=totalUsdt,proto3" json:"total_usdt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangePos) Reset()         { *m = ExchangePos{} }
func (m *ExchangePos) String() string { return proto.CompactTextString(m) }
func (*ExchangePos) ProtoMessage()    {}
func (*ExchangePos) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{34}
}

func (m *ExchangePos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangePos.Unmarshal(m, b)
}
func (m *ExchangePos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangePos.Marshal(b, m, deterministic)
}
func (m *ExchangePos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangePos.Merge(m, src)
}
func (m *ExchangePos) XXX_Size() int {
	return xxx_messageInfo_ExchangePos.Size(m)
}
func (m *ExchangePos) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangePos.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangePos proto.InternalMessageInfo

func (m *ExchangePos) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ExchangePos) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *ExchangePos) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *ExchangePos) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

func (m *ExchangePos) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ExchangePos) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ExchangePos) GetTotalUsdt() string {
	if m != nil {
		return m.TotalUsdt
	}
	return ""
}

type ExchangePosResp struct {
	ExchangePos          []*ExchangePos `protobuf:"bytes,1,rep,name=exchange_pos,json=exchangePos,proto3" json:"exchange_pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExchangePosResp) Reset()         { *m = ExchangePosResp{} }
func (m *ExchangePosResp) String() string { return proto.CompactTextString(m) }
func (*ExchangePosResp) ProtoMessage()    {}
func (*ExchangePosResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{35}
}

func (m *ExchangePosResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangePosResp.Unmarshal(m, b)
}
func (m *ExchangePosResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangePosResp.Marshal(b, m, deterministic)
}
func (m *ExchangePosResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangePosResp.Merge(m, src)
}
func (m *ExchangePosResp) XXX_Size() int {
	return xxx_messageInfo_ExchangePosResp.Size(m)
}
func (m *ExchangePosResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangePosResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangePosResp proto.InternalMessageInfo

func (m *ExchangePosResp) GetExchangePos() []*ExchangePos {
	if m != nil {
		return m.ExchangePos
	}
	return nil
}

type UserStrategyRunReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyId           string   `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStrategyRunReq) Reset()         { *m = UserStrategyRunReq{} }
func (m *UserStrategyRunReq) String() string { return proto.CompactTextString(m) }
func (*UserStrategyRunReq) ProtoMessage()    {}
func (*UserStrategyRunReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{36}
}

func (m *UserStrategyRunReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategyRunReq.Unmarshal(m, b)
}
func (m *UserStrategyRunReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategyRunReq.Marshal(b, m, deterministic)
}
func (m *UserStrategyRunReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategyRunReq.Merge(m, src)
}
func (m *UserStrategyRunReq) XXX_Size() int {
	return xxx_messageInfo_UserStrategyRunReq.Size(m)
}
func (m *UserStrategyRunReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategyRunReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategyRunReq proto.InternalMessageInfo

func (m *UserStrategyRunReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStrategyRunReq) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

type EvaDaily struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ProfitDaily          string   `protobuf:"bytes,2,opt,name=profit_daily,json=profitDaily,proto3" json:"profit_daily,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvaDaily) Reset()         { *m = EvaDaily{} }
func (m *EvaDaily) String() string { return proto.CompactTextString(m) }
func (*EvaDaily) ProtoMessage()    {}
func (*EvaDaily) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{37}
}

func (m *EvaDaily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaDaily.Unmarshal(m, b)
}
func (m *EvaDaily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaDaily.Marshal(b, m, deterministic)
}
func (m *EvaDaily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaDaily.Merge(m, src)
}
func (m *EvaDaily) XXX_Size() int {
	return xxx_messageInfo_EvaDaily.Size(m)
}
func (m *EvaDaily) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaDaily.DiscardUnknown(m)
}

var xxx_messageInfo_EvaDaily proto.InternalMessageInfo

func (m *EvaDaily) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *EvaDaily) GetProfitDaily() string {
	if m != nil {
		return m.ProfitDaily
	}
	return ""
}

type UserStrategyEvaResp struct {
	RealizeProfit        string      `protobuf:"bytes,1,opt,name=realize_profit,json=realizeProfit,proto3" json:"realize_profit,omitempty"`
	RateReturnYear       string      `protobuf:"bytes,2,opt,name=rate_return_year,json=rateReturnYear,proto3" json:"rate_return_year,omitempty"`
	RateReturn           string      `protobuf:"bytes,3,opt,name=rate_return,json=rateReturn,proto3" json:"rate_return,omitempty"`
	EvaDailyList         []*EvaDaily `protobuf:"bytes,4,rep,name=eva_daily_list,json=evaDailyList,proto3" json:"eva_daily_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserStrategyEvaResp) Reset()         { *m = UserStrategyEvaResp{} }
func (m *UserStrategyEvaResp) String() string { return proto.CompactTextString(m) }
func (*UserStrategyEvaResp) ProtoMessage()    {}
func (*UserStrategyEvaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b09d4b2f07a8c73, []int{38}
}

func (m *UserStrategyEvaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStrategyEvaResp.Unmarshal(m, b)
}
func (m *UserStrategyEvaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStrategyEvaResp.Marshal(b, m, deterministic)
}
func (m *UserStrategyEvaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStrategyEvaResp.Merge(m, src)
}
func (m *UserStrategyEvaResp) XXX_Size() int {
	return xxx_messageInfo_UserStrategyEvaResp.Size(m)
}
func (m *UserStrategyEvaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStrategyEvaResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserStrategyEvaResp proto.InternalMessageInfo

func (m *UserStrategyEvaResp) GetRealizeProfit() string {
	if m != nil {
		return m.RealizeProfit
	}
	return ""
}

func (m *UserStrategyEvaResp) GetRateReturnYear() string {
	if m != nil {
		return m.RateReturnYear
	}
	return ""
}

func (m *UserStrategyEvaResp) GetRateReturn() string {
	if m != nil {
		return m.RateReturn
	}
	return ""
}

func (m *UserStrategyEvaResp) GetEvaDailyList() []*EvaDaily {
	if m != nil {
		return m.EvaDailyList
	}
	return nil
}

func init() {
	proto.RegisterType((*StrategyProfitCompensateReq)(nil), "StrategyProfitCompensateReq")
	proto.RegisterType((*SymbolWithRate)(nil), "symbolWithRate")
	proto.RegisterType((*SymbolRankWithRateYearResp)(nil), "SymbolRankWithRateYearResp")
	proto.RegisterType((*AssertsResp)(nil), "AssertsResp")
	proto.RegisterType((*TradeSymbolReq)(nil), "TradeSymbolReq")
	proto.RegisterType((*Symbol)(nil), "Symbol")
	proto.RegisterType((*GetSymbolsResp)(nil), "GetSymbolsResp")
	proto.RegisterType((*ExChangeList)(nil), "ExChangeList")
	proto.RegisterType((*UserApiReq)(nil), "UserApiReq")
	proto.RegisterType((*UserApiKeyReq)(nil), "UserApiKeyReq")
	proto.RegisterType((*ExchangeApi)(nil), "ExchangeApi")
	proto.RegisterType((*ExchangeApiResp)(nil), "ExchangeApiResp")
	proto.RegisterType((*UpdateExchangeApiReq)(nil), "UpdateExchangeApiReq")
	proto.RegisterType((*GetExApiReq)(nil), "GetExApiReq")
	proto.RegisterType((*ExApiResp)(nil), "ExApiResp")
	proto.RegisterType((*GetTradeListReq)(nil), "GetTradeListReq")
	proto.RegisterType((*TradeListResp)(nil), "TradeListResp")
	proto.RegisterType((*ProfitReq)(nil), "profitReq")
	proto.RegisterType((*ProfitRealTimeResp)(nil), "ProfitRealTimeResp")
	proto.RegisterType((*GetExchangePosReq)(nil), "GetExchangePosReq")
	proto.RegisterType((*GetStrategyReq)(nil), "GetStrategyReq")
	proto.RegisterType((*UserStrategyListResp)(nil), "UserStrategyListResp")
	proto.RegisterType((*SetUserStrategyApiReq)(nil), "SetUserStrategyApiReq")
	proto.RegisterType((*UserStrategyDetailReq)(nil), "UserStrategyDetailReq")
	proto.RegisterType((*UserStrategy)(nil), "UserStrategy")
	proto.RegisterType((*UserStrategyWithRate)(nil), "UserStrategyWithRate")
	proto.RegisterType((*StrategyList)(nil), "StrategyList")
	proto.RegisterType((*StrategyReq)(nil), "StrategyReq")
	proto.RegisterType((*SetUserStrategyBalanceReq)(nil), "SetUserStrategyBalanceReq")
	proto.RegisterType((*GetStrategyDetail)(nil), "GetStrategyDetail")
	proto.RegisterType((*Strategy)(nil), "Strategy")
	proto.RegisterType((*CreateStrategyReq)(nil), "CreateStrategyReq")
	proto.RegisterType((*TradeReq)(nil), "tradeReq")
	proto.RegisterType((*OrderReq)(nil), "orderReq")
	proto.RegisterType((*ExchangePos)(nil), "exchangePos")
	proto.RegisterType((*ExchangePosResp)(nil), "ExchangePosResp")
	proto.RegisterType((*UserStrategyRunReq)(nil), "UserStrategyRunReq")
	proto.RegisterType((*EvaDaily)(nil), "evaDaily")
	proto.RegisterType((*UserStrategyEvaResp)(nil), "UserStrategyEvaResp")
}

func init() { proto.RegisterFile("exorder.proto", fileDescriptor_2b09d4b2f07a8c73) }

var fileDescriptor_2b09d4b2f07a8c73 = []byte{
	// 1852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x18, 0x4d, 0x6f, 0x23, 0x49,
	0x35, 0x6d, 0xc7, 0x76, 0xfa, 0xf9, 0x23, 0x49, 0x6d, 0x32, 0xe3, 0xf1, 0xcc, 0x92, 0xd9, 0x1a,
	0x40, 0x59, 0xb4, 0xaa, 0x40, 0x66, 0x17, 0x56, 0xec, 0x05, 0x27, 0xb1, 0x42, 0x04, 0x0c, 0xa1,
	0x93, 0x59, 0x04, 0x1c, 0xac, 0x8a, 0x5d, 0xc9, 0x34, 0xd3, 0xee, 0xee, 0xe9, 0xae, 0xb6, 0xe2,
	0xb9, 0xf1, 0x1f, 0xe0, 0x77, 0x20, 0x21, 0x0e, 0x9c, 0x90, 0xb8, 0x72, 0xe2, 0xce, 0x7f, 0x41,
	0xa8, 0xbe, 0xba, 0xab, 0xed, 0xd8, 0x19, 0x14, 0x0e, 0x7b, 0xab, 0xf7, 0xaa, 0xea, 0xd5, 0xfb,
	0xfe, 0x28, 0x68, 0xb3, 0xdb, 0x28, 0x19, 0xb3, 0x84, 0xc4, 0x49, 0xc4, 0xa3, 0xde, 0xd3, 0x9b,
	0x28, 0xba, 0x09, 0xd8, 0x81, 0x84, 0xae, 0xb2, 0xeb, 0x03, 0x36, 0x89, 0xf9, 0x4c, 0x6f, 0xee,
	0xcd, 0x6f, 0x72, 0x7f, 0xc2, 0x52, 0x4e, 0x27, 0xb1, 0x3a, 0x80, 0x2f, 0xe1, 0xe9, 0x05, 0x4f,
	0x28, 0x67, 0x37, 0xb3, 0xf3, 0x24, 0xba, 0xf6, 0xf9, 0x71, 0x34, 0x89, 0x59, 0x98, 0x52, 0xce,
	0x3c, 0xf6, 0x0e, 0xed, 0x41, 0x33, 0xd5, 0xdb, 0x43, 0x7f, 0xdc, 0x75, 0x9e, 0x3b, 0xfb, 0xae,
	0x07, 0x06, 0x75, 0x36, 0x46, 0x3b, 0x50, 0x8b, 0x13, 0x7f, 0xc4, 0xba, 0x95, 0xe7, 0xce, 0xbe,
	0xe3, 0x29, 0x00, 0x7f, 0x0d, 0x9d, 0x74, 0x36, 0xb9, 0x8a, 0x82, 0x5f, 0xfb, 0xfc, 0x8d, 0x47,
	0x39, 0x43, 0x8f, 0xa0, 0xae, 0x30, 0x9a, 0x86, 0x86, 0x50, 0x0f, 0x36, 0x04, 0xad, 0xdf, 0x30,
	0x9a, 0x48, 0x12, 0xae, 0x97, 0xc3, 0x68, 0x0b, 0xaa, 0x59, 0x12, 0x74, 0xab, 0x12, 0x2d, 0x96,
	0xb8, 0x0f, 0xbd, 0x0b, 0x79, 0xcf, 0xa3, 0xe1, 0x5b, 0x43, 0x5b, 0x9c, 0xf5, 0x58, 0x1a, 0xa3,
	0x17, 0xb0, 0x3e, 0xa6, 0x9c, 0x76, 0x9d, 0xe7, 0xd5, 0xfd, 0xe6, 0xe1, 0x26, 0x29, 0xb3, 0xe0,
	0xc9, 0x4d, 0xcc, 0xa0, 0xd9, 0x4f, 0x53, 0x96, 0xf0, 0x54, 0xde, 0xe9, 0x42, 0x83, 0x2a, 0x50,
	0x33, 0x66, 0x40, 0xc1, 0x71, 0x2c, 0x35, 0xa2, 0xf9, 0xd2, 0x10, 0xfa, 0x36, 0xb4, 0xd5, 0xea,
	0x9c, 0x25, 0x23, 0x16, 0x72, 0xcd, 0x5f, 0x19, 0x89, 0x7f, 0x02, 0x9d, 0xcb, 0x84, 0x8e, 0x99,
	0x66, 0x97, 0xbd, 0x13, 0x92, 0xb2, 0xdb, 0xd1, 0x1b, 0x1a, 0xde, 0x30, 0xfd, 0x54, 0x0e, 0x23,
	0x04, 0xeb, 0xa3, 0xc8, 0x0f, 0xf5, 0x4b, 0x72, 0x8d, 0xff, 0xe8, 0x40, 0x5d, 0xdd, 0x5e, 0xa5,
	0xbc, 0x81, 0x21, 0xa9, 0x95, 0x67, 0x60, 0x61, 0x98, 0x94, 0x53, 0xce, 0x24, 0x7b, 0x35, 0x4f,
	0x01, 0xe2, 0xa1, 0x2c, 0xf4, 0x79, 0x77, 0x5d, 0x3d, 0x24, 0xd6, 0x85, 0x09, 0x6b, 0x12, 0xa9,
	0x00, 0xf1, 0xa6, 0xa6, 0x5c, 0x57, 0x6f, 0x2a, 0x08, 0xbf, 0x84, 0xce, 0x29, 0xe3, 0x8a, 0x31,
	0xa5, 0xc2, 0x4f, 0xa0, 0xa1, 0xf8, 0x49, 0xb5, 0xe6, 0x1b, 0x44, 0x4b, 0x6d, 0xf0, 0xf8, 0x33,
	0x68, 0x0d, 0x6e, 0x8f, 0x25, 0x81, 0x9f, 0xfb, 0x29, 0x47, 0xcf, 0xc0, 0x35, 0xb2, 0x2b, 0xbd,
	0xb7, 0xbc, 0x02, 0x81, 0xbf, 0x02, 0x78, 0x9d, 0xb2, 0xa4, 0x1f, 0xfb, 0x42, 0x6f, 0x8f, 0xa1,
	0x91, 0xa5, 0x2c, 0x29, 0xdc, 0xaf, 0x2e, 0x40, 0xe5, 0x7a, 0xfd, 0xd8, 0x3f, 0x3b, 0x91, 0xa2,
	0x57, 0x3d, 0x05, 0xe0, 0x3e, 0xb4, 0xf5, 0xe5, 0x9f, 0xb1, 0xd9, 0xca, 0xfb, 0x8f, 0xa1, 0x41,
	0x63, 0x7f, 0xf8, 0x96, 0xcd, 0x8c, 0x85, 0xa9, 0xbc, 0x84, 0xff, 0xe4, 0x40, 0xd3, 0xe8, 0xb1,
	0x1f, 0xfb, 0x42, 0x15, 0x82, 0xe4, 0xd9, 0x89, 0x21, 0xa0, 0x20, 0xf4, 0x2d, 0x00, 0x73, 0x2c,
	0xe7, 0xc2, 0xc2, 0x88, 0x7b, 0x8a, 0x0d, 0xed, 0x22, 0x1a, 0x12, 0xf8, 0x0b, 0x36, 0x4a, 0x98,
	0x31, 0x83, 0x86, 0x04, 0xbd, 0x73, 0x9a, 0xa6, 0xf1, 0x9b, 0x84, 0xa6, 0xc6, 0x1a, 0x16, 0x06,
	0xff, 0xc3, 0x81, 0x4d, 0x8b, 0x2f, 0xa9, 0xfc, 0xa5, 0xd2, 0xed, 0x41, 0xd3, 0x68, 0x54, 0x6c,
	0x6a, 0xee, 0x0c, 0xea, 0x6c, 0x8c, 0x5e, 0x88, 0x44, 0xa2, 0x0f, 0x84, 0x74, 0xc2, 0x34, 0x93,
	0x2d, 0x83, 0x7c, 0x45, 0x27, 0xcc, 0xd6, 0xd1, 0xba, 0xad, 0x23, 0xe9, 0x92, 0x4a, 0x86, 0x9a,
	0x76, 0xc9, 0x5c, 0x86, 0xb8, 0x90, 0x41, 0xb9, 0x8e, 0x85, 0xc1, 0x7f, 0x75, 0x60, 0xe7, 0x75,
	0x3c, 0xa6, 0x9c, 0x95, 0x24, 0x79, 0xf7, 0x4d, 0x51, 0x72, 0xe1, 0x55, 0x75, 0xdb, 0xab, 0xbe,
	0x0b, 0xcd, 0x53, 0xc6, 0x07, 0xb7, 0xf7, 0xf8, 0x24, 0xfe, 0x14, 0x5c, 0x7d, 0x28, 0x8d, 0x85,
	0x97, 0x4b, 0x40, 0xb8, 0xbc, 0xf1, 0xf2, 0x1c, 0x81, 0xff, 0xe0, 0xc0, 0xe6, 0x29, 0xe3, 0x32,
	0x4b, 0x08, 0xc4, 0x4a, 0x5f, 0x9d, 0xcb, 0xc3, 0x95, 0x85, 0x3c, 0xdc, 0x85, 0x46, 0x4c, 0x6f,
	0xd8, 0xab, 0x6c, 0xa2, 0x03, 0xde, 0x80, 0x22, 0x49, 0x88, 0xe5, 0x85, 0xff, 0x9e, 0x49, 0x55,
	0xd4, 0xbc, 0x1c, 0xc6, 0xbf, 0x80, 0xb6, 0xf5, 0xbe, 0x62, 0x39, 0x47, 0x18, 0x96, 0x73, 0x84,
	0xd0, 0x1d, 0x17, 0xc0, 0x71, 0x94, 0x85, 0x2a, 0x2d, 0xd6, 0x3c, 0x0b, 0x83, 0x07, 0xe0, 0xaa,
	0x2c, 0xf8, 0x20, 0x59, 0xf0, 0xe7, 0x80, 0xce, 0x35, 0x19, 0x1a, 0x5c, 0xfa, 0x13, 0x26, 0x59,
	0x13, 0x9e, 0x25, 0xb1, 0x16, 0x6f, 0x16, 0x06, 0xff, 0x14, 0xb6, 0xa5, 0x89, 0x94, 0x67, 0x9c,
	0x47, 0xe9, 0x4a, 0x26, 0xec, 0x6c, 0x5c, 0x29, 0x67, 0x63, 0xfc, 0xa9, 0x4a, 0x71, 0x9a, 0xa1,
	0x95, 0xf6, 0xfe, 0x1d, 0xec, 0x08, 0x3f, 0x35, 0x67, 0x73, 0x3d, 0x1e, 0x03, 0x92, 0x17, 0x72,
	0x41, 0x03, 0xc5, 0xb4, 0x48, 0x8f, 0xbb, 0xc4, 0xbe, 0x92, 0x97, 0xa7, 0xad, 0x6c, 0x8e, 0x10,
	0xfe, 0x3d, 0xec, 0x5e, 0x30, 0x6e, 0x1f, 0xbe, 0x2f, 0x25, 0xde, 0xeb, 0x26, 0x56, 0x3c, 0x57,
	0x4b, 0x39, 0xef, 0x57, 0xb0, 0x6b, 0x3f, 0x74, 0xc2, 0x38, 0xf5, 0x83, 0x87, 0x99, 0xf1, 0xdf,
	0x0e, 0xb4, 0x6c, 0x9a, 0x0f, 0x60, 0xfb, 0x33, 0x40, 0x31, 0x4d, 0x58, 0xc8, 0x87, 0xf6, 0xb9,
	0x75, 0x19, 0xa1, 0x5b, 0x6a, 0xe7, 0xa2, 0x38, 0x2d, 0x3c, 0x3e, 0xa0, 0xfc, 0x3a, 0x4a, 0x26,
	0x3a, 0xc0, 0x73, 0xd8, 0x56, 0x40, 0xbd, 0x94, 0xd0, 0xba, 0xd0, 0xb8, 0xa2, 0x01, 0x0d, 0x47,
	0xac, 0xdb, 0x50, 0x8d, 0x80, 0x06, 0x8b, 0x4a, 0xea, 0x5a, 0x95, 0x14, 0xff, 0xa5, 0x5a, 0x36,
	0x7d, 0xde, 0xe9, 0xfc, 0xbf, 0xa5, 0xac, 0x7e, 0x80, 0x94, 0xeb, 0xcb, 0xa5, 0xac, 0x2d, 0x93,
	0xb2, 0xbe, 0x44, 0xca, 0x86, 0xdd, 0x2f, 0xec, 0x42, 0x3d, 0xc9, 0xc2, 0x21, 0xe5, 0xdd, 0x0d,
	0xd5, 0x1c, 0x24, 0x59, 0xd8, 0xe7, 0xe8, 0x13, 0x68, 0xf1, 0x88, 0xd3, 0x60, 0xa8, 0x3b, 0x24,
	0x57, 0x6e, 0x36, 0x25, 0x4e, 0x85, 0x2e, 0xfa, 0x0e, 0x74, 0x12, 0x46, 0x03, 0xff, 0x3d, 0x33,
	0x87, 0x40, 0xf5, 0x49, 0x1a, 0xab, 0x8f, 0x7d, 0x0f, 0xb6, 0xb3, 0x70, 0x38, 0x77, 0xb2, 0x29,
	0x4f, 0x6e, 0x66, 0xa1, 0x57, 0x3a, 0xbb, 0x0f, 0x5b, 0x42, 0xfa, 0x61, 0xc2, 0x78, 0x96, 0x84,
	0xc3, 0x99, 0xe8, 0x19, 0x5b, 0xf2, 0x68, 0x27, 0x91, 0xfd, 0xaa, 0x40, 0xcb, 0xce, 0xb1, 0x68,
	0x98, 0xda, 0x76, 0xc3, 0x84, 0x0f, 0xa1, 0x65, 0x47, 0x18, 0xc2, 0xd0, 0x4a, 0x2d, 0x58, 0x67,
	0x95, 0x12, 0x0e, 0x1f, 0x43, 0xd3, 0x4e, 0x05, 0x56, 0xa2, 0x75, 0x96, 0x27, 0xda, 0xca, 0x5c,
	0xa2, 0x8d, 0xe0, 0xc9, 0x5c, 0x28, 0x1f, 0x29, 0xbd, 0x3f, 0x38, 0xeb, 0x1b, 0x73, 0x0a, 0x37,
	0xa9, 0xe4, 0xe6, 0xc4, 0x2f, 0x64, 0x36, 0x2c, 0x87, 0x33, 0xea, 0x40, 0x45, 0xbf, 0x51, 0xf5,
	0x2a, 0xfe, 0x18, 0xff, 0xd3, 0x81, 0x8d, 0x3c, 0x3a, 0xe7, 0x36, 0x45, 0xab, 0x28, 0xdb, 0x02,
	0xdd, 0x93, 0x8a, 0xb5, 0xe8, 0xc8, 0x2f, 0xe9, 0x8d, 0xe9, 0xc8, 0x2f, 0xe9, 0x8d, 0xd0, 0x74,
	0xc2, 0x26, 0x34, 0x79, 0x6b, 0xca, 0xac, 0x82, 0x16, 0xbb, 0x8b, 0xda, 0x1d, 0xdd, 0xc5, 0x5c,
	0x8f, 0x52, 0x5f, 0xe8, 0x51, 0x76, 0xa0, 0x16, 0xb0, 0x29, 0x0b, 0x8c, 0x53, 0x4a, 0xa0, 0x70,
	0xd5, 0x0d, 0x3b, 0x20, 0xbf, 0x86, 0xed, 0xe3, 0x84, 0x51, 0xce, 0x3e, 0x24, 0x71, 0x6b, 0x69,
	0x2b, 0xb9, 0xb4, 0xcb, 0x35, 0xf9, 0x9f, 0x0a, 0x6c, 0xc8, 0x1a, 0x27, 0xe8, 0x3d, 0xd1, 0xeb,
	0x82, 0x60, 0x43, 0xc2, 0x2a, 0xb5, 0x9a, 0xa7, 0x2a, 0xcb, 0xfa, 0xcc, 0x52, 0xce, 0x15, 0xc4,
	0xe4, 0x20, 0x67, 0x72, 0x99, 0xeb, 0x35, 0x24, 0xbc, 0x68, 0xf9, 0xda, 0x82, 0xe5, 0x9f, 0x81,
	0x3b, 0xf6, 0x13, 0x36, 0xe2, 0x7e, 0x14, 0xea, 0x50, 0x2e, 0x10, 0xc2, 0x2a, 0xd3, 0x28, 0xc8,
	0x26, 0x26, 0x97, 0x69, 0x48, 0xd4, 0xd0, 0x51, 0x34, 0x99, 0xf8, 0x69, 0x2a, 0xae, 0xa9, 0x90,
	0xb6, 0x30, 0xf9, 0x78, 0xe0, 0x5a, 0xe3, 0x41, 0x11, 0x4b, 0x50, 0x1a, 0x3e, 0xf2, 0xb1, 0xa1,
	0x69, 0x8f, 0x0d, 0x5f, 0x18, 0x05, 0x51, 0x2e, 0x63, 0xb3, 0x79, 0xd8, 0x23, 0x6a, 0x06, 0x25,
	0x66, 0x06, 0x25, 0x97, 0x66, 0x06, 0xd5, 0xca, 0xeb, 0xf3, 0x52, 0x39, 0x6e, 0xcf, 0x95, 0xe3,
	0x3f, 0x57, 0xb4, 0x9e, 0xb4, 0x01, 0x72, 0x9d, 0x39, 0x65, 0x9d, 0xfd, 0xef, 0x06, 0xb8, 0x57,
	0xcb, 0xcb, 0xf4, 0xb8, 0x4c, 0x27, 0x4f, 0xc1, 0xbd, 0xca, 0x66, 0x43, 0x5b, 0x2f, 0x1b, 0x57,
	0xd9, 0xec, 0x5c, 0xaa, 0xe6, 0x63, 0x80, 0x94, 0x05, 0x81, 0xde, 0x55, 0x89, 0xcb, 0x15, 0x18,
	0xb5, 0xfd, 0xc4, 0xd2, 0x5c, 0xdb, 0x72, 0xad, 0x39, 0xed, 0x74, 0x16, 0x47, 0x47, 0x69, 0xb2,
	0xcd, 0xc2, 0x64, 0xf8, 0xef, 0x4e, 0x11, 0x58, 0xe7, 0x51, 0xba, 0x74, 0x7e, 0xb4, 0x9c, 0xbe,
	0x52, 0xae, 0x06, 0xcf, 0xc0, 0xa5, 0x53, 0xea, 0x07, 0xf4, 0x2a, 0x30, 0x83, 0x41, 0x81, 0x10,
	0xf4, 0xae, 0x93, 0xe8, 0x3d, 0x0b, 0x4d, 0xd0, 0x2b, 0x48, 0xf0, 0xc2, 0x67, 0xb1, 0x89, 0x75,
	0xb9, 0x2e, 0xdc, 0xa4, 0x6e, 0xbb, 0xc9, 0xc7, 0x00, 0xaa, 0x80, 0x64, 0xe9, 0x98, 0x6b, 0xe5,
	0xba, 0x12, 0xf3, 0x3a, 0x1d, 0x73, 0x7c, 0x54, 0x0c, 0x3a, 0xb2, 0x91, 0x4b, 0x63, 0x74, 0x00,
	0x79, 0xee, 0x18, 0xc6, 0x91, 0x19, 0x35, 0x5b, 0xc4, 0x92, 0xd3, 0xb3, 0x85, 0xc6, 0xaf, 0x00,
	0xd9, 0xf9, 0xd6, 0x13, 0xd5, 0xe4, 0x21, 0xed, 0x4c, 0x1f, 0x36, 0xd8, 0x94, 0x9e, 0x50, 0x3f,
	0x98, 0x09, 0x41, 0xc5, 0x08, 0xa3, 0x49, 0xc8, 0xb5, 0xa8, 0x89, 0xaa, 0x7c, 0x0d, 0xc7, 0xe2,
	0x8c, 0xa6, 0xd0, 0x54, 0x38, 0x79, 0x0d, 0xff, 0xcd, 0x81, 0x8f, 0x6c, 0x9e, 0x06, 0x53, 0x2a,
	0x65, 0x5b, 0xac, 0x95, 0xce, 0x5d, 0xb5, 0xf2, 0xae, 0xfa, 0x57, 0xb9, 0xb3, 0xfe, 0xed, 0x41,
	0xd3, 0x3a, 0xa9, 0x0d, 0x08, 0xc5, 0x21, 0x74, 0x00, 0x1d, 0x36, 0xa5, 0x8a, 0x53, 0xd5, 0x9b,
	0xae, 0x4b, 0x7d, 0xba, 0xc4, 0xc8, 0xe8, 0xb5, 0xcc, 0x4a, 0x54, 0xc1, 0xc3, 0x7f, 0x35, 0xa0,
	0x31, 0xb8, 0xfd, 0xa5, 0x08, 0x35, 0xf4, 0xa3, 0x62, 0x9a, 0x3f, 0x0b, 0xaf, 0x23, 0xf4, 0x68,
	0x21, 0xc2, 0x07, 0x93, 0x98, 0xcf, 0x7a, 0x6d, 0x62, 0x0f, 0xfd, 0x78, 0x0d, 0x7d, 0x09, 0x9d,
	0xfe, 0x78, 0x6c, 0x8f, 0xd6, 0x2d, 0x62, 0x41, 0xbd, 0x25, 0x84, 0xf0, 0x1a, 0xfa, 0x3e, 0x20,
	0xab, 0xb9, 0xd7, 0x23, 0x14, 0x6a, 0x11, 0x6b, 0x28, 0xeb, 0x01, 0xc9, 0x47, 0x2f, 0xbc, 0x86,
	0x4e, 0x60, 0x7b, 0x61, 0xce, 0x44, 0xbb, 0xe4, 0xae, 0xd9, 0x73, 0xc5, 0xbb, 0x3f, 0x86, 0xed,
	0x13, 0x16, 0xb0, 0x32, 0x95, 0x26, 0x29, 0xbe, 0x27, 0x56, 0xdc, 0x3d, 0x84, 0x96, 0x3d, 0xdf,
	0xa1, 0x2d, 0x32, 0x37, 0xee, 0xf5, 0x3a, 0xa4, 0x34, 0x7d, 0xe1, 0x35, 0xf4, 0x43, 0x59, 0xb6,
	0xcb, 0xd3, 0x0f, 0x02, 0x92, 0x4f, 0x55, 0xbd, 0x8f, 0xc8, 0xe2, 0x68, 0x84, 0xd7, 0xd0, 0x0f,
	0x00, 0x06, 0x53, 0x1a, 0x64, 0x54, 0xa6, 0x7f, 0x97, 0x98, 0x82, 0xb5, 0x82, 0xbd, 0x2f, 0xa0,
	0x53, 0x5c, 0xb9, 0x88, 0x23, 0x8e, 0x5c, 0x62, 0xd2, 0xec, 0x8a, 0x6b, 0x5f, 0xca, 0xe1, 0xc8,
	0x8a, 0x4e, 0x84, 0xc8, 0xc2, 0xdc, 0xd5, 0xdb, 0x22, 0x73, 0xf1, 0x2b, 0x1f, 0xcc, 0xe7, 0x5d,
	0xfd, 0x7d, 0x84, 0x36, 0x49, 0xf9, 0x93, 0xac, 0xb7, 0x49, 0xca, 0x9f, 0x4b, 0xd2, 0x90, 0xc2,
	0xf4, 0x73, 0x61, 0x83, 0x1e, 0x91, 0x3b, 0xc7, 0x95, 0xde, 0x0e, 0xb9, 0x23, 0xc0, 0xf0, 0x1a,
	0x7a, 0x09, 0xed, 0x53, 0xc6, 0xd5, 0xdf, 0x80, 0x74, 0xda, 0x0e, 0x29, 0x7d, 0x13, 0x59, 0x1c,
	0x17, 0x3e, 0xf4, 0x39, 0xec, 0x88, 0x4b, 0x69, 0xca, 0x78, 0x7a, 0x34, 0xeb, 0x07, 0x81, 0xfe,
	0x5b, 0x28, 0xfb, 0x5d, 0x8b, 0x58, 0x1f, 0x8a, 0x78, 0x0d, 0x79, 0xf0, 0x24, 0x17, 0x62, 0xfe,
	0x9f, 0x72, 0x69, 0xac, 0x3c, 0x25, 0xcb, 0x3f, 0x36, 0x25, 0xcd, 0xee, 0xb2, 0x6f, 0x5a, 0xf4,
	0x8c, 0xac, 0xf8, 0xc1, 0x5d, 0x6e, 0xc9, 0xa3, 0xc7, 0xbf, 0xdd, 0x25, 0x5f, 0x5d, 0x47, 0x3c,
	0x0b, 0xd9, 0x30, 0x4d, 0xa6, 0xc3, 0x3c, 0x79, 0x3a, 0x57, 0x75, 0x79, 0xf8, 0xe5, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x99, 0x4b, 0xc0, 0x1a, 0x6b, 0x16, 0x00, 0x00,
}
