pipeline{
    agent any

    // 允许颜色输出
//     options {
//       ansiColor('xterm')
//     }
    environment{
        HARBOR_HOST= '192.168.3.30'
        K8S_NAMESPACE='develop'
    }
    parameters {
        string(name: 'PROJECT_NAME', defaultValue: 'api-gateway', description: 'project name,same as the name ofdocker container')
        string(name: 'CONTAINER_VERSION', defaultValue: '', description: 'docker container version number, SET when major version number changed')
        booleanParam(name: 'DEPLOYMENT_K8S', defaultValue: true, description: 'release deployment k8s')
    }
    stages {
        stage('Initial') {
            steps{
                script {
                        env.DOCKER_IMAGE='develop/${PROJECT_NAME}'
                          // 脚本式创建一个环境变量
                        if (params.CONTAINER_VERSION == ''){
//                             env.APP_VERSION = sh(returnStdout:true,script:"jenkins-build-tools gen -p ${params.PROJECT_NAME}").trim()
                        }else {
                            env.APP_VERSION ="${params.CONTAINER_VERSION}-alpha"
                        }
                        sh "echo ${env.APP_VERSION}"
                    }
                }
        }
        stage("Docker Build") {
            when {
                allOf {
                    expression { env.APP_VERSION != null }
                }
            }
            steps("Start Build") {
                sh "./service/common-srv/deploy/build.sh"
            }

        }
        stage("Deploy") {
            when {
                allOf {
                    expression { env.APP_VERSION != null }
                }
            }
            steps("Deploy to kubernetes") {
                script {
                    if (params.DEPLOYMENT_K8S) {
                        sh "./service/common-srv/deploy/deploy.sh"
                    }
                }
            }
        }
    }
    post {
    		always {
    			echo 'One way or another, I have finished'
    			echo sh(returnStdout: true, script: 'env')
    			deleteDir() /* clean up our workspace */
    		}
    		success {
//     			SendDingding("success")
    			echo 'structure success'
    		}
    		failure {
//     			SendDingding("failure")
    			echo 'structure failure'
    		}
    		unsuccessful {
    			//SendDingding("unsuccessful")
    			echo 'structure unsuccessful'
    		}
    		aborted {
    			//SendDingding("aborted")
    			echo 'structure aborted'
    		}
    		unstable {
    			//SendDingding("unstable")
    			echo 'structure unstable'
    		}
       }
}



